logging:
  level: INFO
  appenders:
    - type: file
      currentLogFilename: ./logs/portfolio.log
      archive: false

elasticSearchHost: "localhost"
elasticSearchPort: "9200"
elasticSearchCluster: "personal_site"