server:
  applicationConnectors:
  - type: http
    port: 3333
  adminConnectors:
  - type: http
    port: 3334

elasticSearchHost: "localhost"
elasticSearchPort: "9200"
elasticSearchCluster: "personal_site"